name: messaging_core
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  drift: ^2.15.0
  path_provider: ^2.0.13
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.19+1
  pull_to_refresh: ^2.0.0
  intl: ^0.18.0
  get_it: ^7.6.0
  flutter_screenutil: ^5.7.0
  scrollable_positioned_list: ^0.3.8
  auto_size_text: ^3.0.0
  bot_toast: ^4.1.3
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  skeleton_text: ^3.0.1
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.11
  flutter_linkify: ^6.0.0
  flutter_cache_manager: ^3.3.0
  get: ^4.6.6
  api_handler:
    git: {url: 'https://github.com/ardeshir-33033/api_helper.git', ref: main}


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true
  generate: true

  fonts:
    - family: poppins-extra
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
    - family: poppins-bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: poppins-semibold
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
    - family: poppins-medium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
    - family: poppins-Regular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: poppins-light
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf

  assets:
    - develop.env
    - assets/fonts/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

