name: messaging_core
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  drift: ^2.15.0
  path_provider: ^2.0.13
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.19+1
  pull_to_refresh: ^2.0.0
  intl: ^0.18.0
  get_it: ^7.6.0
  flutter_screenutil: ^5.7.0
  scrollable_positioned_list: ^0.3.8
  extended_nested_scroll_view: 6.1.2
  auto_size_text: ^3.0.0
  bot_toast: ^4.1.3
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  skeleton_text: ^3.0.1
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.11
  flutter_linkify: ^6.0.0
  flutter_cache_manager: ^3.3.0
  responsive_framework: ^1.0.0
  get: ^4.6.6
  dartz: ^0.10.1
  file_picker: ^5.3.2
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  device_info_plus: ^9.0.2
  permission_handler: ^11.0.1
  image: ^4.0.17
  record: ^4.4.4
  just_audio: ^0.9.34
  socket_io_client: ^2.0.3+1
  animated_text_kit: ^4.2.2
  uuid: ^3.0.7
  dio: ^5.0.2
  syncfusion_flutter_sliders: ^22.2.5
  photo_view: ^0.14.0
  image_gallery_saver: ^2.0.3
  open_filex: ^4.3.2
  video_player: ^2.8.2
  contacts_service: ^0.6.3
  emoji_picker_flutter: ^2.0.0
  google_fonts: ^4.0.0
  wakelock_plus: ^1.1.1
  expandable_bottom_sheet: ^1.1.1+1
  connectivity_plus: ^5.0.0
  google_maps_flutter: ^2.6.0
  location: ^5.0.3


  #  http: ^0.13.5
  api_handler:
    git: {url: 'https://github.com/ardeshir-33033/api_helper.git', ref: main}


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true
  generate: true

  fonts:
    - family: Cairo-extra
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
    - family: Cairo-bold
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
    - family: Cairo-semibold
      fonts:
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
    - family: Cairo-medium
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
    - family: Cairo-light
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Light.ttf

  assets:
    - lib/develop.env
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/tones/
    - lib/assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

